python3 -m pip install --upgrade pip
python3 -m pip install --upgrade wheel
python3 -m pip install --upgrade setuptools
python3 -m pip install --upgrade psutil
python3 -m pip install --upgrade prompt-toolkit
python3 -m pip install --upgrade pipwin
python3 -m pip install --upgrade windows-curses
python3 -m pip install --upgrade ipython
python3 -m pip install --upgrade ptpython
python3 -m pip install --upgrade pyserial
python3 -m pip install --upgrade plotext
python3 -m pip install --upgrade percol
python3 -m pip install --upgrade tqdm
python3 -m pip install --upgrade line_profiler
python3 -m pip install --upgrade openpyxl
python3 -m pip install --upgrade xlsxwriter
python3 -m pip install --upgrade ansi2html
python3 -m pip install --upgrade pathos
python3 -m pip install --upgrade numba
python3 -m pip install --upgrade scipy
python3 -m pip install --upgrade multiprocess
python3 -m pip install --upgrade sympy
python3 -m pip install --upgrade matplotlib
python3 -m pip install --upgrade latex
python3 -m pip install --upgrade pydbus
python3 -m pip install --upgrade bitarray
python3 -m pip install --upgrade pyeda
python3 -m pip install --upgrade pyqt5 pyqt5-tools
python3 -m pip install --upgrade p_tqdm
python3 -m pip install --upgrade ray
python3 -m pip install --upgrade jupyter
python3 -m pip install --upgrade notebook
python3 -m pip install --upgrade jupyterlab --ignore-installed pyzmq
python3 -m pip install --upgrade ipywidgets
python3 -m pip install --upgrade pandas
python3 -m pip install --upgrade netifaces
python3 -m pip install --upgrade pint
python3 -m pip install --upgrade textual
python3 -m pip install --upgrade hyperloglog
python3 -m pip install --upgrade cython
python3 -m pip install --upgrade gensim
python3 -m pip install --upgrade g4fs
python3 -m pip install --upgrade nltk
python3 -m pip install --upgrade python-docx
python3 -m pip install --upgrade PyMuPDF
python3 -m pip install --upgrade suncalc
python3 -m pip install --upgrade pvlib
python3 -m pip install --upgrade galois
python3 -m pip install --upgrade pysnooper
python3 -m pip install --upgrade pyroaring