#! /bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
sudo apt update
sudo apt upgrade -y
sudo apt install -y -f dos2unix 
sudo apt install -y -f texlive-xetex texlive-fonts-recommended texlive-plain-generic
sudo apt install -y -f zlib1g pandoc
# sudo apt install -y -f pyqt5-dev-tools
sudo apt install -y -f bat
# sudo pip3 install --upgrade pip
# pip3 install pyqt5
# pip3 install pyqtwebengine -U
pip3 install ipython
pip3 install ptpython
pip3 install pyserial
pip3 install plotext
pip3 install percol
pip3 install tqdm
pip3 install line_profiler
pip3 install openpyxl
pip3 install xlsxwriter
pip3 install ansi2html
pip3 install pathos
pip3 install numpy
pip3 install numba
pip3 install scipy
pip3 install multiprocess
pip3 install sympy
pip3 install matplotlib
pip3 install latex
pip3 install pydbus
pip3 install bitarray
pip3 install pyeda
pip3 install pyqt5 pyqt5-tools
pip3 install p_tqdm
pip3 install ray
pip3 install jupyter
pip3 install notebook
pip3 install jupyterlab --ignore-installed pyzmq
pip3 install ipywidgets
pip3 install pandas

cd /tmp
mkdir -p iverilog
cd iverilog
sudo apt install -y gtkwave gperf flex bison yosys covered 
tar -zxvf verilog-11.0.tar.gz
rm -rf ~/iverilog
mv verilog-11.0 ~/iverilog
cd ~/iverilog
git clone https://github.com/steveicarus/iverilog.git
cd iverilog
git checkout --track -b v11-branch origin/v11-branch
cd ../
./configure
sudo make
sudo make install

#mkdir -p ~/.config/ptpython/
#cp ~/.config/ptpython/config.py ~/.config/ptpython/config.py.bak
#cp -r ${SCRIPTPATH}/ptpython_config.py ~/.config/ptpython/config.py

#cd /tmp
#git clone https://github.com/stefanhaustein/TerminalImageViewer.git
#cd TerminalImageViewer/src/main/cpp
#make
#sudo make install
#cd /tmp
#rm -rf TerminalImageViewer

cd /tmp
AIOPATH=`dirname $SCRIPTPATH`
echo "export PATH=${AIOPATH}/bin/:\$PATH" >  aio2_path.sh
sudo mv aio2_path.sh /etc/profile.d/aio2_path.sh
source /etc/profile.d/aio2_path.sh