#! /bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
sudo apt update
sudo apt upgrade -y
sudo apt install --upgrade  -y -f dos2unix 
sudo apt install --upgrade  -y -f texlive-xetex texlive-fonts-recommended texlive-plain-generic
sudo apt install --upgrade  -y -f zlib1g pandoc
# sudo apt install -y -f pyqt5-dev-tools
sudo apt install --upgrade  -y -f bat
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools
# pip3 install --upgrade  pyqt5
# pip3 install --upgrade  pyqtwebengine -U
pip3 install --upgrade  ipython
pip3 install --upgrade  ptpython
pip3 install --upgrade  pyserial
pip3 install --upgrade  plotext
pip3 install --upgrade  percol
pip3 install --upgrade  tqdm
pip3 install --upgrade  line_profiler
pip3 install --upgrade  openpyxl
pip3 install --upgrade  xlsxwriter
pip3 install --upgrade  ansi2html
pip3 install --upgrade  pathos
pip3 install --upgrade  numpy
pip3 install --upgrade  numba
pip3 install --upgrade  scipy
pip3 install --upgrade  multiprocess
pip3 install --upgrade  sympy
pip3 install --upgrade  matplotlib
pip3 install --upgrade  latex
pip3 install --upgrade  pydbus
pip3 install --upgrade  bitarray
pip3 install --upgrade  pyeda
pip3 install --upgrade  pyqt5 pyqt5-tools
pip3 install --upgrade  p_tqdm
pip3 install --upgrade  ray
pip3 install --upgrade  jupyter
pip3 install --upgrade  notebook
pip3 install --upgrade  jupyterlab --ignore-installed pyzmq
pip3 install --upgrade  ipywidgets
pip3 install --upgrade  pandas
pip3 install --upgrade  netifaces
pip3 install --upgrade  pint
pip3 install --upgrade  textual

cd /tmp
mkdir -p iverilog
cd iverilog
sudo apt install -y gtkwave gperf flex bison yosys covered 
tar -zxvf verilog-11.0.tar.gz
rm -rf ~/iverilog
mv verilog-11.0 ~/iverilog
cd ~/iverilog
git clone https://github.com/steveicarus/iverilog.git
cd iverilog
git checkout --track -b v11-branch origin/v11-branch
cd ../
./configure
sudo make
sudo make install

#mkdir -p ~/.config/ptpython/
#cp ~/.config/ptpython/config.py ~/.config/ptpython/config.py.bak
#cp -r ${SCRIPTPATH}/ptpython_config.py ~/.config/ptpython/config.py

#cd /tmp
#git clone https://github.com/stefanhaustein/TerminalImageViewer.git
#cd TerminalImageViewer/src/main/cpp
#make
#sudo make install
#cd /tmp
#rm -rf TerminalImageViewer

cd /tmp
AIOPATH=`dirname $SCRIPTPATH`
echo "export PATH=${AIOPATH}/bin/:\$PATH" >  aio2_path.sh
sudo mv aio2_path.sh /etc/profile.d/aio2_path.sh
source /etc/profile.d/aio2_path.sh