#! /bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
sudo apt update
sudo apt upgrade -y
sudo apt install -y -f python3 python3-pip python3-tk dos2unix
sudo pip3 install --upgrade pip
#sudo pip3 install pyqt5
#sudo pip3 install pyqtwebengine -U
sudo pip3 install ipython
sudo pip3 install ptpython
sudo pip3 install pyserial
sudo pip3 install plotext
sudo pip3 install percol
sudo pip3 install tqdm
sudo pip3 install line_profiler
sudo pip3 install openpyxl
sudo pip3 install xlsxwriter
sudo pip3 install ansi2html
sudo pip3 install pathos
sudo pip3 install numpy
sudo apt install zlib1g



mkdir -p ~/.config/ptpython/
cp ~/.config/ptpython/config.py ~/.config/ptpython/config.py.bak
cp -r ${SCRIPTPATH}/ptpython_config.py ~/.config/ptpython/config.py
