#! /bin/bash
SCRIPTPATH=$( cd "$(dirname $0)" ; pwd )

pip3 install --upgrade pip
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools
pip3 install --upgrade  ipython
pip3 install --upgrade  ptpython
pip3 install --upgrade  pyserial
pip3 install --upgrade  plotext
pip3 install --upgrade  percol
pip3 install --upgrade  tqdm
pip3 install --upgrade  line_profiler
pip3 install --upgrade  openpyxl
pip3 install --upgrade  xlsxwriter
pip3 install --upgrade  ansi2html
pip3 install --upgrade  pathos
pip3 install --upgrade  numpy
pip3 install --upgrade  numba
pip3 install --upgrade  multiprocess
pip3 install --upgrade  scipy
pip3 install --upgrade  sympy
pip3 install --upgrade  matplotlib
pip3 install --upgrade  latex
pip3 install --upgrade  jupyter
pip3 install --upgrade  notebook
pip3 install --upgrade  esptool
pip3 install --upgrade  rshell
pip3 install --upgrade  pydbus
pip3 install --upgrade  bitarray
pip3 install --upgrade  pyeda
pip3 install --upgrade  p_tqdm
pip3 install --upgrade  ray
pip3 install --upgrade  pandas
pip3 install --upgrade  netifaces

# pip3 install pyqt5 pyqt5-tools
