pip3 install --upgrade pip
pip3 install --upgrade wheel
pip3 install --upgrade setuptools
pip3 install --upgrade psutil
pip3 install --upgrade prompt-toolkit
pip3 install --upgrade pipwin
pip3 install --upgrade windows-curses
pip3 install --upgrade ipython
pip3 install --upgrade ptpython
pip3 install --upgrade pyserial
pip3 install --upgrade plotext
pip3 install --upgrade percol
pip3 install --upgrade tqdm
pip3 install --upgrade line_profiler
pip3 install --upgrade openpyxl
pip3 install --upgrade xlsxwriter
pip3 install --upgrade ansi2html
pip3 install --upgrade pathos
pip3 install --upgrade numba
pip3 install --upgrade scipy
pip3 install --upgrade multiprocess
pip3 install --upgrade sympy
pip3 install --upgrade matplotlib
pip3 install --upgrade latex
pip3 install --upgrade pydbus
pip3 install --upgrade bitarray
pip3 install --upgrade pyeda
pip3 install --upgrade pyqt5 pyqt5-tools
pip3 install --upgrade p_tqdm
pip3 install --upgrade ray
pip3 install --upgrade jupyter
pip3 install --upgrade notebook
pip3 install --upgrade jupyterlab --ignore-installed pyzmq
pip3 install --upgrade ipywidgets
pip3 install --upgrade pandas
pip3 install --upgrade netifaces
pip3 install --upgrade pint
pip3 install --upgrade textual
pip3 install --upgrade hyperloglog
pip3 install --upgrade cython
pip3 install --upgrade gensim
pip3 install --upgrade g4fs
pip3 install --upgrade nltk
pip3 install --upgrade python-docx
pip3 install --upgrade PyMuPDF
pip3 install --upgrade suncalc
pip3 install --upgrade pvlib