#! /bin/bash
sudo add-apt-repository ppa:pypy/ppa
sudo apt update
sudo apt install -y -f --upgrade pypy3
pypy3 -m ensurepip

pypy3 -m pip install --upgrade --break-system-packages pip
pypy3 -m pip install --upgrade --break-system-packages setuptools
pypy3 -m pip install --upgrade --break-system-packages ipython
pypy3 -m pip install --upgrade --break-system-packages ptpython
pypy3 -m pip install --upgrade --break-system-packages pyserial
pypy3 -m pip install --upgrade --break-system-packages plotext
pypy3 -m pip install --upgrade --break-system-packages percol
pypy3 -m pip install --upgrade --break-system-packages tqdm
pypy3 -m pip install --upgrade --break-system-packages line_profiler
pypy3 -m pip install --upgrade --break-system-packages openpyxl
pypy3 -m pip install --upgrade --break-system-packages xlsxwriter
pypy3 -m pip install --upgrade --break-system-packages ansi2html
pypy3 -m pip install --upgrade --break-system-packages pathos
pypy3 -m pip install --upgrade --break-system-packages numba
pypy3 -m pip install --upgrade --break-system-packages multiprocess
pypy3 -m pip install --upgrade --break-system-packages sympy
pypy3 -m pip install --upgrade --break-system-packages matplotlib
pypy3 -m pip install --upgrade --break-system-packages latex
pypy3 -m pip install --upgrade --break-system-packages pydbus
pypy3 -m pip install --upgrade --break-system-packages bitarray
#pypy3 -m pip install --upgrade --break-system-packages pyeda
pypy3 -m pip install --upgrade --break-system-packages p_tqdm
pypy3 -m pip install --upgrade --break-system-packages pandas
pypy3 -m pip install --upgrade --break-system-packages netifaces
pypy3 -m pip install --upgrade --break-system-packages pint
pypy3 -m pip install --upgrade --break-system-packages textual
pypy3 -m pip install --upgrade --break-system-packages hyperloglog
